**Based on accuracy score we chose model for our data - Model SVM**

Support Vector Machine model showed best accuracy score result (0.82028)

Importing the libraries

In [252]:
import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd

Importing the training dataset

In [253]:
dataset = pd.read_csv('bank_loan_main.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3,7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [254]:
dataset.head()

Loan ID  ... Tax Liens
0  14dd8831-6af5-400b-83ec-68e61888a048  ...       0.0
1  4771cc26-131a-45db-b5aa-537ea4ba5342  ...       0.0
2  4eed4e6a-aa2f-4c91-8651-ce984ee8fb26  ...       0.0
3  77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a  ...       0.0
4  d4062e70-befa-4995-8643-a0de73938182  ...       0.0

[5 rows x 19 columns]

In [255]:
dataset.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105768 entries, 0 to 105767
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Loan ID                       105768 non-null  object 
 1   Customer ID                   105768 non-null  object 
 2   Loan Status                   105768 non-null  object 
 3   Current Loan Amount           105768 non-null  object 
 4   Term                          105767 non-null  object 
 5   Credit Score                  85532 non-null   float64
 6   Annual Income                 85533 non-null   float64
 7   Years in current job          101302 non-null  object 
 8   Home Ownership                105768 non-null  object 
 9   Purpose                       105768 non-null  object 
 10  Monthly Debt                  105768 non-null  float64
 11  Years of Credit History       105768 non-null  float64
 12  Months since last delinquent  49611 non-null

In [256]:
#dataset.drop(["Loan ID", "Customer ID", "Home Ownership", "Purpose","Monthly Debt","Months since last delinquent","Number of Open Accounts",\
#              "Maximum Open Credit","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22","Unnamed: 23","Unnamed: 24","Unnamed: 25","Unnamed: 26"], axis =1, inplace=True)
dataset.drop(["Loan ID", "Customer ID", "Home Ownership", "Purpose","Monthly Debt","Months since last delinquent","Number of Open Accounts",\
              "Maximum Open Credit"], axis =1, inplace=True)

In [257]:
dataset.head()

Loan Status Current Loan Amount  ... Bankruptcies  Tax Liens
0  Fully Paid              445412  ...          1.0        0.0
1  Fully Paid              262328  ...          0.0        0.0
2  Fully Paid            99999999  ...          0.0        0.0
3  Fully Paid              347666  ...          0.0        0.0
4  Fully Paid              176220  ...          0.0        0.0

[5 rows x 11 columns]

Taking care of missing data

In [258]:
dataset.isnull().sum()

Loan Status                      0
Current Loan Amount              0
Term                             1
Credit Score                 20236
Annual Income                20235
Years in current job          4466
Years of Credit History          0
Number of Credit Problems        0
Current Credit Balance           0
Bankruptcies                   221
Tax Liens                       11
dtype: int64

In [259]:
dataset.dropna(inplace = True)  #droping rows with null

In [260]:
dataset.isnull().sum()

Loan Status                  0
Current Loan Amount          0
Term                         0
Credit Score                 0
Annual Income                0
Years in current job         0
Years of Credit History      0
Number of Credit Problems    0
Current Credit Balance       0
Bankruptcies                 0
Tax Liens                    0
dtype: int64

In [261]:
dataset.head()

Loan Status Current Loan Amount  ... Bankruptcies  Tax Liens
0   Fully Paid              445412  ...          1.0        0.0
2   Fully Paid            99999999  ...          0.0        0.0
3   Fully Paid              347666  ...          0.0        0.0
5  Charged Off              206602  ...          0.0        0.0
6   Fully Paid              217646  ...          1.0        0.0

[5 rows x 11 columns]

In [262]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81752 entries, 0 to 105766
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Loan Status                81752 non-null  object 
 1   Current Loan Amount        81752 non-null  object 
 2   Term                       81752 non-null  object 
 3   Credit Score               81752 non-null  float64
 4   Annual Income              81752 non-null  float64
 5   Years in current job       81752 non-null  object 
 6   Years of Credit History    81752 non-null  float64
 7   Number of Credit Problems  81752 non-null  int64  
 8   Current Credit Balance     81752 non-null  int64  
 9   Bankruptcies               81752 non-null  float64
 10  Tax Liens                  81752 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 7.5+ MB


In [263]:
dataset["Loan Status"].value_counts()

Fully Paid     64620
Charged Off    17132
Name: Loan Status, dtype: int64

In [264]:
Loan_Status = dataset[["Loan Status"]]
dataset = dataset.drop(["Loan Status"], axis=1)
dataset = pd.concat([dataset, Loan_Status], axis =1 )
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81752 entries, 0 to 105766
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Current Loan Amount        81752 non-null  object 
 1   Term                       81752 non-null  object 
 2   Credit Score               81752 non-null  float64
 3   Annual Income              81752 non-null  float64
 4   Years in current job       81752 non-null  object 
 5   Years of Credit History    81752 non-null  float64
 6   Number of Credit Problems  81752 non-null  int64  
 7   Current Credit Balance     81752 non-null  int64  
 8   Bankruptcies               81752 non-null  float64
 9   Tax Liens                  81752 non-null  float64
 10  Loan Status                81752 non-null  object 
dtypes: float64(5), int64(2), object(4)
memory usage: 7.5+ MB


In [265]:

X = dataset.iloc[:, [0,1,2,3,4,5,6,7,8,9]].values
y = dataset.iloc[:, 10].values    #status of loan


Encoding the Independent Variable (col: Loan_Term)

In [266]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder  #import class that will proceed with encoding
ColTrnsfm = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ColTrnsfm.fit_transform(X))

In [267]:
X

array([[0.0, 1.0, 445412, ..., 228190, 1.0, 0.0],
       [0.0, 1.0, 99999999, ..., 297996, 0.0, 0.0],
       [1.0, 0.0, 347666, ..., 256329, 0.0, 0.0],
       ...,
       [0.0, 1.0, 99999999, ..., 153045, 0.0, 0.0],
       [0.0, 1.0, 103136, ..., 109554, 1.0, 0.0],
       [0.0, 1.0, 530332, ..., 404225, 0.0, 0.0]], dtype=object)

Encoding the Dependent Variable (Col: Loan_Status)

In [268]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [269]:
y

array([1, 1, 1, ..., 1, 1, 1])

**Splitting the Dataset into the training and Test Sets**

In [270]:
#3. Splitting the Dataset into the training and Test Sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [271]:
X_train

array([[1.0, 0.0, 247808, ..., 76893, 0.0, 0.0],
       [0.0, 1.0, '99999999', ..., 279642, 0.0, 0.0],
       [0.0, 1.0, '460702', ..., 641250, 0.0, 0.0],
       ...,
       [0.0, 1.0, 134904, ..., 464455, 0.0, 0.0],
       [0.0, 1.0, 99999999, ..., 269914, 0.0, 0.0],
       [0.0, 1.0, '66572', ..., 51243, 0.0, 0.0]], dtype=object)

**Feature Scaling - Standardisation**

In [272]:
#Standardisation-recommended [-3:3] vs Normalisation [0:1] for specifc situations
#note: not applied to encoded indep variables
from sklearn.preprocessing import StandardScaler #Standartisation 
sc = StandardScaler()

X_train[:, 2:] = sc.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc.transform(X_test[:, 2:])

In [273]:
X_train

array([[1.0, 0.0, -0.40801105985865543, ..., -0.5654689559070466,
        -0.32824994821247483, -0.11123980461393151],
       [0.0, 1.0, 2.4630075305103962, ..., -0.04487291834503262,
        -0.32824994821247483, -0.11123980461393151],
       [0.0, 1.0, -0.40188364926595954, ..., 0.883623360061888,
        -0.32824994821247483, -0.11123980461393151],
       ...,
       [0.0, 1.0, -0.4112606073590911, ..., 0.4296690793464405,
        -0.32824994821247483, -0.11123980461393151],
       [0.0, 1.0, 2.4630075305103962, ..., -0.06985138064769883,
        -0.32824994821247483, -0.11123980461393151],
       [0.0, 1.0, -0.4132273054371022, ..., -0.6313301358066548,
        -0.32824994821247483, -0.11123980461393151]], dtype=object)

**Training the SVM Model on the Training DataSet**

In [274]:
from sklearn.svm import SVC
classifier = SVC(C = 0.25, kernel= 'linear')
classifier.fit(X_train, y_train)

SVC(C=0.25, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Predicting the Test set results

In [275]:
y_pred = classifier.predict(X_test)

Making the Confusion Matrix

In [276]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  896  2544]
 [    0 12911]]


0.8444131857378754

From confusion matrix, we see that we dont have false negative, but we have some false positive. 84% of Accuracy result is not bad. We will improve it further with Grid Search

**Save the model to reuse it again**

In [277]:
import pickle

In [278]:
file = open('Bank_Loan_SVM.pkl', 'wb')

# dump information to that file
pickle.dump(classifier, file)

In [279]:
model = open('Bank_Loan_SVM.pkl','rb') # 'wb' - to open file in binary format for writing, 'rb' - in binary for reading

In [280]:
SVM = pickle.load(model)

In [281]:
y_prediction = SVM.predict(X_test)

In [282]:
accuracy_score(y_test, y_prediction)

0.8444131857378754